export { DashboardPage } from './dashboard'
export { CategoriesListPage, CategoryFormPage } from './categories'
export { BrandsListPage, BrandFormPage } from './brands'
export { ProductsListPage, ProductFormPage } from './products'
export { CollectionsListPage, CollectionFormPage } from './collections'
export { ContentArticlesListPage, ContentArticleFormPage } from './content-articles'
export { FeedbackRequestsPage } from './feedback'
